#!/bin/bash


_repolink () {
    local regex
    regex='(https?)://github.com/.+/.+'
    if [[ $VISA_REPO == "VisaBot" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL0QzS1JJU0gvRDN2aWxVc2VyYm90L2FyY2hpdmUvbWFzdGVyLnppcA==" | base64 -d
    elif [[ $VISA_REPO == "Visabot" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL0QzS1JJU0gvRDN2aWxVc2VyYm90L2FyY2hpdmUvbWFzdGVyLnppcA==" | base64 -d
    elif [[ $VISA_REPO =~ $regex ]]
    then
        if [[ $VISA_REPO_BRANCH ]]
        then
            echo "${VISA_REPO}/archive/${VISA_REPO_BRANCH}.zip"
        else
            echo "${VISA_REPO}/archive/master.zip"
        fi
    else
        echo "aHR0cHM6Ly9naXRodWIuY29tL0QzS1JJU0gvRDN2aWxVc2VyYm90L2FyY2hpdmUvbWFzdGVyLnppcA==" | base64 -d
    fi
}


start_bot () {
    local zippath
    zippath="myvisabot.zip"
    echo "  Downloading source code ..."
    wget -q $(_repolink) -O "$zippath"
    echo "  Unpacking Data ..."
    D3VILPATH=$(zipinfo -1 "$zippath" | grep -v "/.");
    unzip -qq "$zippath"
    echo "  Processing Codes..."
    rm -rf "$zippath"
    sleep 5
    cd $D3VILPATH
    echo "  • Starting VisaBot •  "

    python3 ../setup/updater.py ../requirements.txt requirements.txt
    python3 -m visabot
}

start_bot
